services:
  strapi:
    image: prawee/strapi
    container_name: 68_s3_APKPP_app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}
    ports:
      - "16000:1337"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    external: true