services:
  strapi:
    image: prawee/strapi
    container_name: strapi
    restart: always

    env_file:
      - .env

    environment:
      NODE_ENV: production

      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}

      APP_KEYS: key1,key2,key3,key4
      API_TOKEN_SALT: randomtoken
      ADMIN_JWT_SECRET: adminsecret
      JWT_SECRET: jwtsecret

    volumes:
      - ./strapi:/srv/app

    ports:
      - "1337:1337"

    networks:
      - backend