services:
  caddy:
    image: caddy:2
    container_name: 68_s3_APKPP_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

volumes:
  caddy_data:
  caddy_config:

networks:
  backend:
    external: true
