services:
  APKPP:
    image: postgres:latest
    container_name: APKPP_DB
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports: 
      - ${DATABASE_PORT}:5432